language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
      - libsqlite3-dev
before_script:
  - rustup set profile minimal
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
