[package]
name = "rssdownloader-rs"
version = "0.1.0"
authors = ["Tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "1.10.0"
regex = "1.4.3"
signal-hook = "0.2.3"
toml = "0.5.8"
chrono = "0.4.19"
log = "0.4.14"
reqwest = { version = "0.11.0", features = ["gzip", "blocking"] }
dirs = "3.0.1"
rusqlite = { version = "0.24.2", features = ["bundled"] }
log4rs = "1.0.0"
clap = "2.33.3"
