[package]
name = "rssdownloader-rs"
version = "0.1.0"
authors = ["Tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "1.9.0"
regex = "1.3.9"
signal-hook = "0.1.16"
toml = "0.5.6"
chrono = "0.4.15"
log = "0.4.11"
reqwest = { version = "0.10.7", features = ["gzip", "blocking"] }
dirs = "3.0.1"
rusqlite = { version = "0.24.0", features = ["bundled"] }
log4rs = "0.13.0"
clap = "2.33.3"
