[package]
name = "rssdownloader-rs"
version = "0.1.0"
authors = ["Tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0.2"
regex = "1.7.2"
signal-hook = "0.3.15"
toml = "0.5.11"
chrono = "0.4.24"
log = "0.4.17"
reqwest = { version = "0.11.15", features = ["gzip", "blocking"] }
dirs = "4.0.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
clap = "4.1.11"
fern = { version = "0.6.1", features = ["colored"] }
lazy_static = "1.4.0"
