[package]
name = "rssdownloader-rs"
version = "0.1.0"
authors = ["Tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0.1"
regex = "1.5.5"
signal-hook = "0.3.13"
toml = "0.5.8"
chrono = "0.4.19"
log = "0.4.16"
reqwest = { version = "0.11.10", features = ["gzip", "blocking"] }
dirs = "4.0.0"
rusqlite = { version = "0.27.0", features = ["bundled"] }
log4rs = "1.0.0"
clap = "3.1.14"
