[package]
name = "rssdownloader-rs"
version = "0.1.0"
authors = ["Tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = { version = "1.9.0", features = ["from_url"] }
regex = "1.3.4"
signal-hook = "0.1.13"
toml = "0.5.6"
chrono = "0.4.10"
log = "0.4.8"
fern = { version = "0.5.9", features = ["colored"] }
reqwest = { version = "0.10.1", features = ["blocking"] }
futures = "0.3.4"
tokio = { version = "0.2.11", features = ["full"] }
dirs = "2.0.2"
