[package]
name = "rssdownloader-rs"
version = "0.1.0"
authors = ["Tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0.1"
regex = "1.6.0"
signal-hook = "0.3.14"
toml = "0.5.9"
chrono = "0.4.22"
log = "0.4.17"
reqwest = { version = "0.11.12", features = ["gzip", "blocking"] }
dirs = "4.0.0"
rusqlite = { version = "0.28.0", features = ["bundled"] }
clap = "4.0.15"
fern = "0.6.1"
