[package]
name = "rssdownloader-rs"
version = "0.1.0"
authors = ["Tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "1.9.0"
regex = "1.3.6"
signal-hook = "0.1.13"
toml = "0.5.6"
chrono = "0.4.11"
log = "0.4.8"
fern = { version = "0.6.0", features = ["colored"] }
reqwest = { version = "0.10.4", features = ["gzip"] }
futures = "0.3.4"
tokio = { version = "0.2.13", features = ["full"] }
dirs = "2.0.2"
rusqlite = "0.21.0"
