[package]
name = "rssdownloader-rs"
version = "0.1.0"
authors = ["Tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "1.9.0"
regex = "1.4.2"
signal-hook = "0.2.1"
toml = "0.5.7"
chrono = "0.4.19"
log = "0.4.11"
reqwest = { version = "0.10.10", features = ["gzip", "blocking"] }
dirs = "3.0.1"
rusqlite = { version = "0.24.1", features = ["bundled"] }
log4rs = "0.13.0"
clap = "2.33.3"
