[package]
name = "rssdownloader-rs"
version = "0.1.0"
authors = ["Tolien <tolien@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss = "2.0.6"
regex = "1.10.2"
signal-hook = "0.3.17"
toml = "0.8.6"
log = "0.4.20"
reqwest = { version = "0.11.22", features = ["gzip", "blocking"] }
dirs = "5.0.1"
rusqlite = { version = "0.29.0", features = ["bundled"] }
log4rs = "1.2.0"
clap = "4.4.7"
time = "0.3.30"
